apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-mongodb-pv.yaml
  - 03-mongodb-pvc.yaml
  - 04-configmap.yaml
  - 05-secrets.yaml
  - 06-mongodb-service.yaml
  - 07-mongodb-statefulset.yaml
  - 08-easyshop-deployment.yaml
  - 09-easyshop-service.yaml
  - 10-ingress.yaml
  - 11-hpa.yaml
  - 12-migration-job.yaml  

  # - ingress.yaml        # optional
  # - pdb.yaml            # optional

commonLabels:
  managed-by: kustomize

# commonAnnotations:
#   owner: platform-team

# images:
#   - name: my-app
#     newName: myrepo/my-app
#     newTag: latest    # overridden in overlays

# configMapGenerator:
#   - name: app-config
#     literals:
#       - LOG_LEVEL=info
#       - FEATURE_X=false

# generatorOptions:
#   disableNameSuffixHash: false
